name: Java CI with Maven - DevVault-v2.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: maven

      - name: Create `.env.properties` file
        run: |
          echo "KEYCLOAK_REALM_ADMIN_USER_USERNAME=${{ secrets.KEYCLOAK_REALM_ADMIN_USER_USERNAME }}" >> .env.properties
          echo "KEYCLOAK_REALM_ADMIN_USER_PASSWORD=${{ secrets.KEYCLOAK_REALM_ADMIN_USER_PASSWORD }}" >> .env.properties
          echo "KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}" >> .env.properties
          echo "KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}" >> .env.properties

      - name: Build and test with Maven
        run: mvn clean install
        env:
          KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          KEYCLOAK_REALM_ADMIN_USER_USERNAME: ${{ secrets.KEYCLOAK_REALM_ADMIN_USER_USERNAME }}
          KEYCLOAK_REALM_ADMIN_USER_PASSWORD: ${{ secrets.KEYCLOAK_REALM_ADMIN_USER_PASSWORD }}